### PR TITLE
fix some grammar errors

### PR DESCRIPTION
**Pull request by fgsoftware1**
-i fix some portuguese grammar errors
-i create .gitignore file to prevent commit od .dccache file(generated by vscode)

### CODE REVIEW

**Comment by oliverklee** [comment]
Thanks for contributing!

However, this is unofficial unmonitored mirror, and patches aren't accepted here. Please post them on wine-devel mailing list instead: https://wiki.winehq.org/Submitting_Patches

**Comment by fgsoftware1** [comment]
> Thanks for contributing!
> 
> However, this is unofficial unmonitored mirror, and patches aren't accepted here. Please post them on wine-devel mailing list instead: https://wiki.winehq.org/Submitting_Patches

how?

**Comment by oliverklee** [comment]
@fgsoftware1 Please have a look at https://wiki.winehq.org/Submitting_Patches - the workflow is explained there.

**Comment by fgsoftware1** [comment]
i have seen but i create a patch trough cms and no file generated and no errors

**Comment by oliverklee** [comment]
I recommend asking on the wine-devel mailing list for help with contributing. (I'm not a Wine developer/contributor, just an interested user who tries to help people who happen to post PRs here. :-) )

**Comment by fgsoftware1** [comment]
ok thanks

**Comment by Neustradamus** [comment]
Dear @wine-mirror team,

I would like to know who manage this organization and this repository.

Thanks in advance.

**Pull request closed without merging**
